@startuml

title __EXPRESSIONS's Class Diagram__\n

  package spec.concordion {
    package spec.concordion.common.command {
      package spec.concordion.common.command.expressions {
        class ComplexExpressionsTest {
            - simple : Evaluator
            - ognl : Evaluator
            + ComplexExpressionsTest()
            + checkExpression()
            - isExpressionSupportedBy()
            - toTableText()
            - initTestVariables()
        }
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.command {
      package spec.concordion.common.command.expressions {
        class SimpleTestFixture {
            + property : String
            + arrayProperty : String[]
            + mapProperty : Map<String, String>
            + method()
            + methodWithArg()
            + methodWithArgs()
            + methodReturningArray()
            + methodReturningMap()
            + methodReturningComplex()
            + methodReturningChain()
        }
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.command {
      package spec.concordion.common.command.expressions {
        class OgnlTestFixture {
        }
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.command {
      package spec.concordion.common.command.expressions {
        class Complex {
            + nestedProperty : String
            + nestedMethod()
            + nestedMethodWithArg()
            + nestedMethodWithArgs()
        }
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.command {
      package spec.concordion.common.command.expressions {
        class Chain {
            + chain()
            + chainWithArg()
            + chainWithArgs()
        }
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.command {
      package spec.concordion.common.command.expressions {
        class ExpressionsTest {
            + isValidEvaluationExpression()
            + isValidSetVariableExpression()
        }
      }
    }
  }
  

  ComplexExpressionsTest +-down- SimpleTestFixture
  ComplexExpressionsTest +-down- OgnlTestFixture
  ComplexExpressionsTest +-down- Complex
  ComplexExpressionsTest +-down- Chain
  SimpleTestFixture o-- Complex : complexProperty
  SimpleTestFixture o-- Chain : chainProperty
  OgnlTestFixture -up-|> SimpleTestFixture
  Chain o-- Complex : chain


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
