@startuml

title __EXTENSION's Class Diagram__\n

  package org.concordion {
    package org.concordion.api {
      package org.concordion.api.extension {
        interface ConcordionExtender {
            {abstract} + withCommand()
            {abstract} + withAssertEqualsListener()
            {abstract} + withAssertTrueListener()
            {abstract} + withAssertFalseListener()
            {abstract} + withExecuteListener()
            {abstract} + withSetListener()
            {abstract} + withRunListener()
            {abstract} + withVerifyRowsListener()
            {abstract} + withThrowableListener()
            {abstract} + withDocumentParsingListener()
            {abstract} + withSpecificationProcessingListener()
            {abstract} + withExampleListener()
            {abstract} + withOuterExampleListener()
            {abstract} + withBuildListener()
            {abstract} + withResource()
            {abstract} + withEmbeddedCSS()
            {abstract} + withEmbeddedCSS()
            {abstract} + withLinkedCSS()
            {abstract} + withEmbeddedJavaScript()
            {abstract} + withLinkedJavaScript()
            {abstract} + withSource()
            {abstract} + withTarget()
            {abstract} + withSpecificationLocator()
            {abstract} + withRunStrategy()
            {abstract} + withBreadcrumbRenderer()
            {abstract} + withSpecificationType()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.api {
      package org.concordion.api.extension {
        interface ConcordionExtension {
            {abstract} + addTo()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.api {
      package org.concordion.api.extension {
        interface ConcordionExtensionFactory {
            {abstract} + createExtension()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.api {
      package org.concordion.api.extension {
        interface Extension {
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.api {
      package org.concordion.api.extension {
        interface Extensions {
            {abstract} + value()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
