@startuml

title __WHITESPACE's Class Diagram__\n

  package spec.concordion {
    package spec.concordion.common.command {
      package spec.concordion.common.command.assertEquals {
        package spec.concordion.common.command.assertEquals.whitespace {
          class LineContinuationsTest {
              - snippets : List<String>
              + addSnippet()
              + processSnippets()
          }
        }
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.command {
      package spec.concordion.common.command.assertEquals {
        package spec.concordion.common.command.assertEquals.whitespace {
          class Result {
              + successes : String
              + failures : String
          }
        }
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.command {
      package spec.concordion.common.command.assertEquals {
        package spec.concordion.common.command.assertEquals.whitespace {
          class NormalizationTest {
          }
        }
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.command {
      package spec.concordion.common.command.assertEquals {
        package spec.concordion.common.command.assertEquals.whitespace {
          class WhitespaceTest {
              + whichSnippetsSucceed()
              + whichSnippetsFail()
              {static} - which()
              - fails()
              - succeeds()
              + normalize()
              {static} - replaceNamedWhitespaceWithRealWhitespaceCharacters()
              {static} - replaceRealWhitespaceCharactersWithNames()
          }
        }
      }
    }
  }
  

  LineContinuationsTest +-down- Result


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
