package app.view;

import app.controller.Controller;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

public class LogInUser extends javax.swing.JFrame {

    private Controller controller;

    /**
     * Creates new form LogInUser
     */
    public LogInUser() {
        this.controller = Controller.getInstance();
        initComponents();
        getContentPane().setBackground(new Color(153, 204, 255));
        this.setVisible(true);
    }

    /**
     * Clears input from the text fields.
     *
     */
    private void clearInput(){
        txtNick.setText("");
        txtPassWord.setText("");
    }

    /**
     * Gives direct access to the app. Debug purpose.
     *
     * @param e picture clicked event
     */
    private void logoStubMouseClicked(MouseEvent e) {
        StUB app = new StUB(controller.getUserInst("ajaleo"), this);
        dispose();
    }

    /**
     * Creates new User.
     *
     * @param e accept button clicked
     */
    private void btAcceptActionPerformed(ActionEvent e) {
        String nick = txtNick.getText();
        String passWord = String.valueOf(txtPassWord.getPassword());
        if(controller.loginSuccesful(nick, passWord)){
            StUB app = new StUB(controller.getUserInst(nick), this);
            clearInput();
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,
                    "Comprueba que los datos son correctos.",
                    "StUB - No se puede iniciar sesión",
                    JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - sasdfgty
    private void initComponents() {
        lblNick = new JLabel();
        jScrollPane1 = new JScrollPane();
        txtNick = new JTextPane();
        lblPassWord = new JLabel();
        txtPassWord = new JPasswordField();
        btAccept = new JButton();
        lblRegister = new JLabel();
        panel1 = new JPanel();
        logoStub = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("StUB - Inicio de sesi\u00f3n");
        Container contentPane = getContentPane();

        //---- lblNick ----
        lblNick.setFont(new Font("Dialog", Font.BOLD, 16));
        lblNick.setText("Usuario:");
        lblNick.setLabelFor(txtNick);

        //======== jScrollPane1 ========
        {

            //---- txtNick ----
            txtNick.setFont(new Font("Dialog", Font.PLAIN, 16));
            jScrollPane1.setViewportView(txtNick);
        }

        //---- lblPassWord ----
        lblPassWord.setFont(new Font("Dialog", Font.BOLD, 16));
        lblPassWord.setText("Contrase\u00f1a:");
        lblPassWord.setToolTipText("");
        lblPassWord.setLabelFor(txtPassWord);

        //---- txtPassWord ----
        txtPassWord.setFont(new Font("Dialog", Font.PLAIN, 16));

        //---- btAccept ----
        btAccept.setFont(new Font("Dialog", Font.BOLD, 16));
        btAccept.setText("Entrar");
        btAccept.setToolTipText("");
        btAccept.addActionListener(e -> btAcceptActionPerformed(e));

        //---- lblRegister ----
        lblRegister.setText("<HTML><U>¿Todavía no te has registrado? ¡Regístrate aquí!</U></HTML>"



        );
        lblRegister.setFont(new Font("Dialog", lblRegister.getFont().getStyle() | Font.BOLD, 16));
        lblRegister.setForeground(new Color(51, 102, 255));
        lblRegister.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                lblRegisterMouseClicked(e);
            }
        });

        //======== panel1 ========
        {

            // JFormDesigner evaluation mark
            panel1.setBorder(new javax.swing.border.CompoundBorder(
                new javax.swing.border.TitledBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0),
                    "JFormDesigner Evaluation", javax.swing.border.TitledBorder.CENTER,
                    javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Dialog", java.awt.Font.BOLD, 12),
                    java.awt.Color.red), panel1.getBorder())); panel1.addPropertyChangeListener(new java.beans.PropertyChangeListener(){public void propertyChange(java.beans.PropertyChangeEvent e){if("border".equals(e.getPropertyName()))throw new RuntimeException();}});


            GroupLayout panel1Layout = new GroupLayout(panel1);
            panel1.setLayout(panel1Layout);
            panel1Layout.setHorizontalGroup(
                panel1Layout.createParallelGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
            );
            panel1Layout.setVerticalGroup(
                panel1Layout.createParallelGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
            );
        }

        //---- logoStub ----
        logoStub.setIcon(new ImageIcon(getClass().getResource("/app/resources/logoStUB.PNG")));
        logoStub.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                logoStubMouseClicked(e);
            }
        });

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNick)
                                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                .addComponent(lblPassWord)
                                .addComponent(txtPassWord, GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addComponent(logoStub)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblRegister, GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                                .addComponent(btAccept, GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
                            .addContainerGap())))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(lblNick)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblPassWord)
                            .addGap(16, 16, 16)
                            .addComponent(txtPassWord, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addComponent(logoStub))
                    .addGap(18, 18, 18)
                    .addComponent(btAccept, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(lblRegister, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(panel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exits the app.
     *
     * @param evt label clicked event
     */
    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btCancelActionPerformed

    /**
     * Opens register form.
     *
     * @param evt label clicked event
     */
    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
        RegisterUser register = new RegisterUser(this);
    }//GEN-LAST:event_lblRegisterMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - sasdfgty
    private JLabel lblNick;
    private JScrollPane jScrollPane1;
    private JTextPane txtNick;
    private JLabel lblPassWord;
    private JPasswordField txtPassWord;
    private JButton btAccept;
    private JLabel lblRegister;
    private JPanel panel1;
    private JLabel logoStub;
    // End of variables declaration//GEN-END:variables
}
