package app.view;

import app.controller.Controller;
import app.model.Episode;
import java.awt.*;
import java.util.Hashtable;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.LayoutStyle;
import javax.swing.border.*;

public class RateEpisode extends javax.swing.JFrame {

    private ViewEpisode parent;
    private Controller controller;
    private Episode episode;

    /**
     * Creates new form RateEpisode
     */
    public RateEpisode(ViewEpisode parent, Episode ep) {
        this.parent = parent;
        this.controller = Controller.getInstance();
        this.episode = ep;
        setVisible(true);
        initComponents();
        initSlider();
    }

    /**
     * Initializes slider.
     *
     */
    private void initSlider(){
        java.awt.Font asd = new java.awt.Font("Dialog", 1, 16);
        Hashtable<Integer, JLabel> labels = new Hashtable();
        labels.put(0, new JLabel("Bad"));
        labels.put(1, new JLabel("Meh"));
        labels.put(2, new JLabel("Sad"));
        labels.put(3, new JLabel("Good"));
        labels.put(4, new JLabel("Wow"));
        for(int i = 0; i <= 4; i++){
            labels.get(i).setFont(asd);
        }
        selEmo.setLabelTable(labels);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - sasdfgty
    private void initComponents() {
        lblTitle = new JLabel();
        lblPerson = new JLabel();
        txtPerson = new JTextField();
        lblDisp = new JLabel();
        selDisp = new JComboBox<>();
        selEmo = new JSlider();
        btAccept = new JButton();
        btCancel = new JButton();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("StUB - Valorar episodio");
        Container contentPane = getContentPane();

        //---- lblTitle ----
        lblTitle.setFont(new Font("Dialog", Font.BOLD, 22));
        lblTitle.setText("Valorar episodio");

        //---- lblPerson ----
        lblPerson.setFont(new Font("Dialog", Font.BOLD, 16));
        lblPerson.setText("Personaje favorito: ");

        //---- txtPerson ----
        txtPerson.setFont(new Font("Dialog", Font.PLAIN, 16));

        //---- lblDisp ----
        lblDisp.setFont(new Font("Dialog", Font.BOLD, 16));
        lblDisp.setText("Dispositivo:");

        //---- selDisp ----
        selDisp.setFont(new Font("Dialog", Font.PLAIN, 16));
        selDisp.setModel(new DefaultComboBoxModel<>(new String[] {
            "Ninguno",
            "Ordenador",
            "SmartPhone / Tablet",
            "SmartTV",
            "Otro"
        }));

        //---- selEmo ----
        selEmo.setFont(new Font("Dialog", Font.BOLD, 16));
        selEmo.setMaximum(4);
        selEmo.setPaintLabels(true);
        selEmo.setPaintTicks(true);
        selEmo.setSnapToTicks(true);
        selEmo.setValue(2);
        selEmo.addMouseWheelListener(e -> selEmoMouseWheelMoved(e));

        //---- btAccept ----
        btAccept.setFont(new Font("Dialog", Font.BOLD, 16));
        btAccept.setText("Aceptar");
        btAccept.addActionListener(e -> {
			btAcceptActionPerformed(e);
			btAcceptActionPerformed(e);
		});

        //---- btCancel ----
        btCancel.setFont(new Font("Dialog", Font.BOLD, 16));
        btCancel.setText("Cancelar");
        btCancel.setBorder(new MatteBorder(1, 1, 1, 1, Color.red));
        btCancel.addActionListener(e -> btCancelActionPerformed(e));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblTitle))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(contentPaneLayout.createParallelGroup()
                                .addGroup(contentPaneLayout.createSequentialGroup()
                                    .addGroup(contentPaneLayout.createParallelGroup()
                                        .addComponent(lblDisp)
                                        .addComponent(lblPerson))
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtPerson, GroupLayout.PREFERRED_SIZE, 240, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(selDisp, GroupLayout.PREFERRED_SIZE, 240, GroupLayout.PREFERRED_SIZE)))
                                .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addComponent(selEmo, GroupLayout.PREFERRED_SIZE, 407, GroupLayout.PREFERRED_SIZE)
                                    .addGroup(contentPaneLayout.createSequentialGroup()
                                        .addComponent(btAccept, GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(btCancel, GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))))))
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(lblTitle)
                    .addGap(37, 37, 37)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPerson)
                        .addComponent(txtPerson, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDisp)
                        .addComponent(selDisp, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(selEmo, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(btAccept, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                        .addComponent(btCancel, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Changes slider value with the mouse wheel.
     *
     * @param evt mouse wheel moved event
     */
    private void selEmoMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_selEmoMouseWheelMoved
        selEmo.setValue(selEmo.getValue() - evt.getUnitsToScroll()/3);
    }//GEN-LAST:event_selEmoMouseWheelMoved

    /**
     * Saves a rating.
     *
     * @param evt accept button clicked event
     */
    private void btAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcceptActionPerformed
        controller.rateEpisode(parent.getUser().getId(), episode.getIdSerie(), String.valueOf(episode.getSeasonNumber()), episode.getTitle(), String.valueOf(selEmo.getValue()));
        dispose();
    }//GEN-LAST:event_btAcceptActionPerformed

    /**
     * Cancels the operation.
     *
     * @param evt cancel button clicked event
     */
    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - sasdfgty
    private JLabel lblTitle;
    private JLabel lblPerson;
    private JTextField txtPerson;
    private JLabel lblDisp;
    private JComboBox<String> selDisp;
    private JSlider selEmo;
    private JButton btAccept;
    private JButton btCancel;
    // End of variables declaration//GEN-END:variables
}
