@startuml

title __FAKE's Class Diagram__\n

  package test.concordion {
    package test.concordion.extension {
      package test.concordion.extension.fake {
        class FakeExtension1 {
            + FakeExtension1()
            + FakeExtension1()
            + addTo()
        }
      }
    }
  }
  

  package test.concordion {
    package test.concordion.extension {
      package test.concordion.extension.fake {
        class FakeExtension2 {
            + FakeExtension2()
            + FakeExtension2()
            + addTo()
        }
      }
    }
  }
  

  package test.concordion {
    package test.concordion.extension {
      package test.concordion.extension.fake {
        class FakeExtension2Factory {
            + FakeExtension2Factory()
            + createExtension()
        }
      }
    }
  }
  

  package test.concordion {
    package test.concordion.extension {
      package test.concordion.extension.fake {
        class FakeExtension3 {
            + FakeExtension3()
            + FakeExtension3()
            + addTo()
        }
      }
    }
  }
  

  package test.concordion {
    package test.concordion.extension {
      package test.concordion.extension.fake {
        abstract class FakeExtensionBase {
            {static} + FAKE_EXTENSION_ATTR_NAME : String
            - text : String
            + FakeExtensionBase()
            + FakeExtensionBase()
            + beforeParsing()
        }
      }
    }
  }
  

  package test.concordion {
    package test.concordion.extension {
      package test.concordion.extension.fake {
        class FakeExtensionWithPrivateConstructor {
            - FakeExtensionWithPrivateConstructor()
            + addTo()
        }
      }
    }
  }
  

  package test.concordion {
    package test.concordion.extension {
      package test.concordion.extension.fake {
        class FakeExtensionWithoutNoArgsConstructor {
            - FakeExtensionWithoutNoArgsConstructor()
            + addTo()
        }
      }
    }
  }
  

  FakeExtension1 -up-|> ConcordionExtension
  FakeExtension1 -up-|> DocumentParsingListener
  FakeExtension1 -up-|> FakeExtensionBase
  FakeExtension2 -up-|> ConcordionExtension
  FakeExtension2 -up-|> DocumentParsingListener
  FakeExtension2 -up-|> FakeExtensionBase
  FakeExtension2Factory -up-|> ConcordionExtensionFactory
  FakeExtension3 -up-|> ConcordionExtension
  FakeExtension3 -up-|> DocumentParsingListener
  FakeExtension3 -up-|> FakeExtensionBase
  FakeExtensionWithPrivateConstructor -up-|> ConcordionExtension
  FakeExtensionWithPrivateConstructor -up-|> DocumentParsingListener
  FakeExtensionWithPrivateConstructor -up-|> FakeExtensionBase
  FakeExtensionWithoutNoArgsConstructor -up-|> ConcordionExtension
  FakeExtensionWithoutNoArgsConstructor -up-|> DocumentParsingListener
  FakeExtensionWithoutNoArgsConstructor -up-|> FakeExtensionBase


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
