@startuml

title __SUPPORT's Class Diagram__\n

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.parser.support {
        class Attribute {
            + name : String
            + value : String
            + Attribute()
            + toString()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.parser.support {
        class ConciseExpressionParser {
            {static} - COMMAND_VALUE_PATTERN : Pattern
            - sourcePrefix : String
            - targetPrefix : String
            - namespaces : Map<String, String>
            + ConciseExpressionParser()
            + ConciseExpressionParser()
            + parse()
            + parse()
            - createStatementFromNamespacePrefix()
            - parseStatement()
            + parseCommandValueAndAttributes()
            + parseCommandValueAndAttributes()
            + isExecuteCommand()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.parser.support {
        class ConcordionStatement {
            + command : Attribute
            + text : String
            + attributes : List<Attribute>
            + ConcordionStatement()
            + withAttribute()
            + withText()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.parser.support {
        class ConcordionSyntaxException {
            {static} - serialVersionUID : long
            + ConcordionSyntaxException()
            + ConcordionSyntaxException()
            + ConcordionSyntaxException()
            + ConcordionSyntaxException()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
