@startuml

title __EXTENSION's Class Diagram__\n

  package spec.concordion {
    package spec.concordion.common.extension {
      abstract class AbstractExtensionTestCase {
          - eventList : List<String>
          - extension : ConcordionExtension
          - helper : ScopedObjectHolder<ExtensionTestHelper>
          + processAnything()
          + process()
          # configureTestRig()
          + getLogStream()
          + getEventLog()
          + isAvailable()
          # getProcessingResult()
          # setExtension()
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.extension {
      class CSSExtensionTest {
          {static} + SOURCE_PATH : String
          {static} + TEST_CSS : String
          + addLinkedCSSExtension()
          + addEmbeddedCSSExtension()
          # configureTestRig()
          + hasCSSDeclaration()
          + hasEmbeddedTestCSS()
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.extension {
      class CustomCommandTest {
          + addCommandExtension()
          + getOutput()
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.extension {
      class ExtensionConfigurationTest {
          {static} - CLASS_NAME_PATTERN : Pattern
          + clearConcordionExtensionsSystemProperty()
          + process()
          + process()
          + process()
          - process()
          - compile()
          - getClassName()
          + setSystemProperty()
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.extension {
      class ExtensionTest {
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.extension {
      class ExtensionTestHelper {
          - logStream : PrintStream
          - baos : ByteArrayOutputStream
          + ExtensionTestHelper()
          + getLogStream()
          + getBaos()
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.extension {
      class FileSuffixExtensionsTest {
          + hasBeenProcessed()
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.extension {
      class FileTargetWithSuffix {
          {static} - PROPERTY_OUTPUT_DIR : String
          - suffix : String
          - target : FileTarget
          + FileTargetWithSuffix()
          - getBaseOutputDir()
          + write()
          + copyTo()
          + getOutputStream()
          + delete()
          + exists()
          + resolvedPathFor()
          - rename()
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.extension {
      class JavaScriptExtensionTest {
          {static} + SOURCE_PATH : String
          {static} + TEST_JS : String
          + addLinkedJavaScriptExtension()
          + addEmbeddedJavaScriptExtension()
          # configureTestRig()
          + hasJavaScriptDeclaration()
          + hasEmbeddedTestJavaScript()
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.extension {
      class ResourceExtensionTest {
          + addResourceExtension()
          + addDynamicResourceExtension()
          # configureTestRig()
      }
    }
  }
  

  package spec.concordion {
    package spec.concordion.common.extension {
      class XhtmlExtension {
          + addTo()
      }
    }
  }
  

  AbstractExtensionTestCase o-- TestRig : testRig
  AbstractExtensionTestCase o-- ProcessingResult : processingResult
  CSSExtensionTest -up-|> AbstractExtensionTestCase
  CustomCommandTest -up-|> AbstractExtensionTestCase
  ExtensionConfigurationTest o-- JavaSourceCompiler : compiler
  FileTargetWithSuffix -up-|> Target
  JavaScriptExtensionTest -up-|> AbstractExtensionTestCase
  ResourceExtensionTest -up-|> AbstractExtensionTestCase
  XhtmlExtension -up-|> ConcordionExtension


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
