@startuml

title __LISTENER's Class Diagram__\n

  package org.concordion.internal {
    package org.concordion.internal.listener {
      class BreadcrumbRendererTest {
          {static} - EXPECTED_SOURCE_NAME : String
          {static} - SPEC_RESOURCE_NAME : String
          {static} - PACKAGE_RESOURCE_NAME : String
          {static} - BAD_SPEC_RESOURCE_NAME : String
          {static} - BAD_PACKAGE_RESOURCE_NAME : String
          {static} - ERRONEOUS_HTML : String
          {static} - GOOD_HTML : String
          - renderer : BreadcrumbRenderer
          + systemErrRule : SystemErrRule
          + BreadcrumbRendererTest()
          + logsNameOfErroneousHtmlFileOnParseError()
          + createsBodyIfNoneExists()
          + createsSpanWithParentBreadcrumb()
          + cachesResult()
      }
    }
  }
  

  package org.concordion.internal {
    package org.concordion.internal.listener {
      class DocumentStructureImproverTest {
          - improver : DocumentStructureImprover
          - html : Element
          - document : Document
          + testAddsHeadIfMissing()
          + testTransfersEverythingBeforeBodyIntoNewlyCreatedHead()
      }
    }
  }
  

  package org.concordion.internal {
    package org.concordion.internal.listener {
      class JavaScriptLinkerTest {
          {static} - NOT_NEEDED_PARAMETER : Resource
          + xmlOutputContainsAnExplicitEndTagForScriptElement()
      }
    }
  }
  

  package org.concordion.internal {
    package org.concordion.internal.listener {
      class MetadataCreatorTest {
          - metadataCreator : MetadataCreator
          - html : Element
          - document : Document
          - head : Element
          + MetadataCreatorTest()
          + testAddsContentTypeMetadataIfMissing()
          + testDoesNotAddContentTypeMetadataIfAlreadyPresent()
      }
    }
  }
  

  BreadcrumbRendererTest o-- StubSource : stubSource
  DocumentStructureImproverTest -up-|> TestCase
  MetadataCreatorTest -up-|> TestCase


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
