@startuml

title __SCOPEDOBJECTS's Class Diagram__\n

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.scopedObjects {
        interface ScopedField {
            {abstract} + saveValueFromField()
            {abstract} + loadValueIntoField()
            {abstract} + destroy()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.scopedObjects {
        class ScopedFieldImpl {
            - scopedObject : ScopedObject
            - field : Field
            + ScopedFieldImpl()
            + saveValueFromField()
            + loadValueIntoField()
            + destroy()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.scopedObjects {
        class ScopedFieldStore {
            {static} ~ DEFAULT_EXTENSION_SCOPE : Scope
            - scopedFields : Map<Scope, List<ScopedField>>
            + ScopedFieldStore()
            - createScopedFields()
            - createScopedObjectField()
            - createScopedExtensionField()
            # createScopedObject()
            + saveValueFromFields()
            + loadValuesIntoFields()
            + destroyFields()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.scopedObjects {
        interface ScopedObject {
            {abstract} + getObject()
            {abstract} + setObject()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.scopedObjects {
        enum ScopedObjectFactory {
          SINGLETON
          repository
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.scopedObjects {
        class ScopedObjectImpl {
            - specificationClass : Class<?>
            - fieldName : String
            - fieldScope : Scope
            - repository : ScopedObjectRepository
            + ScopedObjectImpl()
            + getObject()
            + setObject()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.scopedObjects {
        class ScopedObjectRepository {
            - repo : Map<ScopedObjectRepositoryKey, Object>
            + ScopedObjectRepository()
            + getObject()
            + setObject()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.scopedObjects {
        class ScopedObjectRepositoryKey {
            - name : String
            - concordionFieldScope : Scope
            - specificationClass : Class<?>
            + ScopedObjectRepositoryKey()
            + hashCode()
            {static} + hash()
            + equals()
        }
      }
    }
  }
  

  ScopedFieldImpl -up-|> ScopedField
  ScopedObjectImpl -up-|> ScopedObject
  ScopedObjectRepository +-down- ScopedObjectRepositoryKey


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
