@startuml

title __MARKDOWN's Class Diagram__\n

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.parser.markdown {
        class ConcordionHtmlSerializer {
            {static} - URL_FOR_CONCORDION : String
            {static} - SOURCE_CONCORDION_NAMESPACE_PREFIX : String
            - statementParser : ConciseExpressionParser
            - pendingCommand : ConcordionStatement
            - inHeaderNode : boolean
            - inExample : boolean
            - currentExampleHeading : String
            - currentExampleLevel : int
            - depth : int
            - escapeHtmlNodes : boolean
            - escapeText : boolean
            + ConcordionHtmlSerializer()
            + visit()
            + visit()
            - toLinkNode()
            - toLinkNode()
            - visit()
            + visit()
            # printIndentedTag()
            + visit()
            + visit()
            + visit()
            + visit()
            - closeExampleIfNeedeed()
            - closeExample()
            - toExampleName()
            - generateName()
            - printConcordionCommandElement()
            - printPendingConcordionCommand()
            - printConcordionCommand()
            - firstChildOf()
            - firstChildIsInstanceOf()
            - numberOfLinkNodeChildren()
            + visit()
            + visit()
            - firstColumnOfHeaderRow()
            - asLinkNode()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.parser.markdown {
        class ConcordionMarkdownException {
            {static} - serialVersionUID : long
            + ConcordionMarkdownException()
            + ConcordionMarkdownException()
            + ConcordionMarkdownException()
            + ConcordionMarkdownException()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.parser.markdown {
        class LinkNode {
            - url : String
            - title : String
            - text : String
            + LinkNode()
            + getUrl()
            + getTitle()
            + getText()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.parser.markdown {
        class MarkdownConverter {
            {static} - CONCORDION_NAMESPACE_PREFIX : String
            - namespaces : Map<String, String>
            - pegdownExtensions : int
            + convert()
            - asString()
            - wrapBody()
            + withPegdownExtensions()
            + withNamespaceDeclarations()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.parser.markdown {
        class MarkdownParser {
            - pegdownExtensions : int
            - namespaces : Map<String, String>
            + MarkdownParser()
            + MarkdownParser()
            + markdownToHtml()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.parser.markdown {
        class RunCommandLinkRenderer {
            - concordionNamespacePrefix : String
            - runCommandToken : String
            + RunCommandLinkRenderer()
            + render()
        }
      }
    }
  }
  

  package org.concordion {
    package org.concordion.internal {
      package org.concordion.internal.parser.markdown {
        class XhtmlConverter {
            + convert()
        }
      }
    }
  }
  

  MarkdownConverter -up-|> SpecificationConverter
  XhtmlConverter -up-|> SpecificationConverter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
